# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\nruntime.v1\"\x1a\n\tImageSpec\x12\r\n\x05image\x18\x01 \x01(\t\">\n\nAuthConfig\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04\x61uth\x18\x03 \x01(\t\"^\n\x10PullImageRequest\x12$\n\x05image\x18\x01 \x01(\x0b\x32\x15.runtime.v1.ImageSpec\x12$\n\x04\x61uth\x18\x02 \x01(\x0b\x32\x16.runtime.v1.AuthConfig\"&\n\x11PullImageResponse\x12\x11\n\timage_ref\x18\x01 \x01(\t2Z\n\x0eRuntimeService\x12H\n\tPullImage\x12\x1c.runtime.v1.PullImageRequest\x1a\x1d.runtime.v1.PullImageResponseB,Z*k8s.io/cri-api/pkg/apis/runtime/v1;runtimeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*k8s.io/cri-api/pkg/apis/runtime/v1;runtime'
  _globals['_IMAGESPEC']._serialized_start=25
  _globals['_IMAGESPEC']._serialized_end=51
  _globals['_AUTHCONFIG']._serialized_start=53
  _globals['_AUTHCONFIG']._serialized_end=115
  _globals['_PULLIMAGEREQUEST']._serialized_start=117
  _globals['_PULLIMAGEREQUEST']._serialized_end=211
  _globals['_PULLIMAGERESPONSE']._serialized_start=213
  _globals['_PULLIMAGERESPONSE']._serialized_end=251
  _globals['_RUNTIMESERVICE']._serialized_start=253
  _globals['_RUNTIMESERVICE']._serialized_end=343
# @@protoc_insertion_point(module_scope)
